// 中国古代著名诗人时间线数据 (618-1279)
const poets = [
  // 初唐诗人
  {
    name: "王勃",
    dynasty: "初唐",
    birth: 650,
    death: 676,
    peakPeriod: { start: 670, end: 676 },
    description: "初唐四杰之首，《滕王阁序》作者",
    famousWorks: ["滕王阁序", "送杜少府之任蜀州"],
    style: "清新俊逸",
    category: "初唐四杰",
  },
  {
    name: "杨炯",
    dynasty: "初唐",
    birth: 650,
    death: 692,
    peakPeriod: { start: 675, end: 690 },
    description: "初唐四杰之一，以边塞诗著称",
    famousWorks: ["从军行", "出塞"],
    style: "雄健有力",
    category: "初唐四杰",
  },
  {
    name: "卢照邻",
    dynasty: "初唐",
    birth: 634,
    death: 684,
    peakPeriod: { start: 660, end: 680 },
    description: "初唐四杰之一，长于七言歌行",
    famousWorks: ["长安古意", "九月九日玄武山旅眺"],
    style: "华丽绮靡",
    category: "初唐四杰",
  },
  {
    name: "骆宾王",
    dynasty: "初唐",
    birth: 640,
    death: 684,
    peakPeriod: { start: 665, end: 684 },
    description: "初唐四杰之一，《咏鹅》作者",
    famousWorks: ["咏鹅", "在狱咏蝉"],
    style: "慷慨激昂",
    category: "初唐四杰",
  },
  {
    name: "陈子昂",
    dynasty: "初唐",
    birth: 661,
    death: 702,
    peakPeriod: { start: 685, end: 700 },
    description: "唐诗革新的先驱，提倡汉魏风骨",
    famousWorks: ["登幽州台歌", "感遇诗"],
    style: "慷慨悲壮",
    category: "诗歌革新派",
  },

  // 盛唐诗人
  {
    name: "李白",
    dynasty: "盛唐",
    birth: 701,
    death: 762,
    peakPeriod: { start: 725, end: 755 },
    description: "诗仙，浪漫主义诗人的代表",
    famousWorks: ["静夜思", "将进酒", "蜀道难"],
    style: "豪放飘逸",
    category: "浪漫主义",
  },
  {
    name: "杜甫",
    dynasty: "盛唐",
    birth: 712,
    death: 770,
    peakPeriod: { start: 740, end: 770 },
    description: "诗圣，现实主义诗人的代表",
    famousWorks: ["三吏三别", "春望", "茅屋为秋风所破歌"],
    style: "沉郁顿挫",
    category: "现实主义",
  },
  {
    name: "王维",
    dynasty: "盛唐",
    birth: 701,
    death: 761,
    peakPeriod: { start: 730, end: 760 },
    description: "诗佛，山水田园诗派代表",
    famousWorks: ["山居秋暝", "鸟鸣涧", "送元二使安西"],
    style: "清淡自然",
    category: "山水田园派",
  },
  {
    name: "孟浩然",
    dynasty: "盛唐",
    birth: 689,
    death: 740,
    peakPeriod: { start: 715, end: 740 },
    description: "山水田园诗派代表，隐逸诗人",
    famousWorks: ["春晓", "过故人庄", "临洞庭湖赠张丞相"],
    style: "清淡恬静",
    category: "山水田园派",
  },
  {
    name: "高适",
    dynasty: "盛唐",
    birth: 704,
    death: 765,
    peakPeriod: { start: 735, end: 760 },
    description: "边塞诗派代表，与岑参并称",
    famousWorks: ["别董大", "燕歌行"],
    style: "雄浑悲壮",
    category: "边塞诗派",
  },
  {
    name: "岑参",
    dynasty: "盛唐",
    birth: 715,
    death: 770,
    peakPeriod: { start: 745, end: 765 },
    description: "边塞诗派代表，以奇险著称",
    famousWorks: ["白雪歌送武判官归京", "走马川行奉送出师西征"],
    style: "奇峭瑰丽",
    category: "边塞诗派",
  },

  // 中唐诗人
  {
    name: "韩愈",
    dynasty: "中唐",
    birth: 768,
    death: 824,
    peakPeriod: { start: 795, end: 820 },
    description: "古文运动领袖，以文为诗",
    famousWorks: ["师说", "进学解", "春雪"],
    style: "奇崛险怪",
    category: "古文运动",
  },
  {
    name: "柳宗元",
    dynasty: "中唐",
    birth: 773,
    death: 819,
    peakPeriod: { start: 800, end: 815 },
    description: "古文运动代表，山水诗精品",
    famousWorks: ["江雪", "渔翁", "小石潭记"],
    style: "清峻幽深",
    category: "古文运动",
  },
  {
    name: "白居易",
    dynasty: "中唐",
    birth: 772,
    death: 846,
    peakPeriod: { start: 800, end: 840 },
    description: "新乐府运动倡导者，通俗易懂",
    famousWorks: ["长恨歌", "琵琶行", "赋得古原草送别"],
    style: "平易近人",
    category: "新乐府运动",
  },
  {
    name: "元稹",
    dynasty: "中唐",
    birth: 779,
    death: 831,
    peakPeriod: { start: 805, end: 825 },
    description: "新乐府运动代表，与白居易并称元白",
    famousWorks: ["离思", "遣悲怀", "菊花"],
    style: "清新自然",
    category: "新乐府运动",
  },
  {
    name: "刘禹锡",
    dynasty: "中唐",
    birth: 772,
    death: 842,
    peakPeriod: { start: 800, end: 835 },
    description: "诗豪，以咏史诗和民歌体著称",
    famousWorks: ["陋室铭", "竹枝词", "乌衣巷"],
    style: "豪迈清新",
    category: "咏史怀古",
  },

  // 晚唐诗人
  {
    name: "李商隐",
    dynasty: "晚唐",
    birth: 813,
    death: 858,
    peakPeriod: { start: 835, end: 855 },
    description: "晚唐诗坛巨匠，以无题诗著称",
    famousWorks: ["无题", "锦瑟", "夜雨寄北"],
    style: "朦胧隐晦",
    category: "象征派",
  },
  {
    name: "杜牧",
    dynasty: "晚唐",
    birth: 803,
    death: 852,
    peakPeriod: { start: 830, end: 850 },
    description: "小杜，以咏史和写景诗著称",
    famousWorks: ["清明", "江南春", "赤壁"],
    style: "俊爽明快",
    category: "咏史抒怀",
  },
  {
    name: "温庭筠",
    dynasty: "晚唐",
    birth: 812,
    death: 870,
    peakPeriod: { start: 840, end: 865 },
    description: "花间派鼻祖，词的重要开拓者",
    famousWorks: ["菩萨蛮", "更漏子", "望江南"],
    style: "浓艳精巧",
    category: "花间派",
  },

  // 五代诗人
  {
    name: "李煜",
    dynasty: "五代",
    birth: 937,
    death: 978,
    peakPeriod: { start: 960, end: 975 },
    description: "南唐后主，词坛巨匠",
    famousWorks: ["虞美人", "浪淘沙", "相见欢"],
    style: "真挚深沉",
    category: "婉约派",
  },
  {
    name: "冯延巳",
    dynasty: "五代",
    birth: 903,
    death: 960,
    peakPeriod: { start: 930, end: 955 },
    description: "南唐词人，对宋词影响深远",
    famousWorks: ["鹊踏枝", "谒金门"],
    style: "清丽婉约",
    category: "婉约派",
  },

  // 北宋诗人
  {
    name: "苏轼",
    dynasty: "北宋",
    birth: 1037,
    death: 1101,
    peakPeriod: { start: 1060, end: 1095 },
    description: "豪放派词人代表，唐宋八大家之一",
    famousWorks: ["水调歌头", "念奴娇·赤壁怀古", "江城子"],
    style: "豪放旷达",
    category: "豪放派",
  },
  {
    name: "王安石",
    dynasty: "北宋",
    birth: 1021,
    death: 1086,
    peakPeriod: { start: 1050, end: 1080 },
    description: "政治家、文学家，唐宋八大家之一",
    famousWorks: ["泊船瓜洲", "元日", "梅花"],
    style: "精炼深刻",
    category: "政治诗派",
  },
  {
    name: "欧阳修",
    dynasty: "北宋",
    birth: 1007,
    death: 1072,
    peakPeriod: { start: 1040, end: 1065 },
    description: "北宋文坛领袖，唐宋八大家之一",
    famousWorks: ["醉翁亭记", "蝶恋花", "采桑子"],
    style: "平易自然",
    category: "古文运动",
  },
  {
    name: "柳永",
    dynasty: "北宋",
    birth: 987,
    death: 1053,
    peakPeriod: { start: 1015, end: 1045 },
    description: "婉约派词人，慢词的开创者",
    famousWorks: ["雨霖铃", "八声甘州", "蝶恋花"],
    style: "缠绵悱恻",
    category: "婉约派",
  },
  {
    name: "黄庭坚",
    dynasty: "北宋",
    birth: 1045,
    death: 1105,
    peakPeriod: { start: 1070, end: 1100 },
    description: "江西诗派开山祖师，苏门四学士之一",
    famousWorks: ["登快阁", "寄黄几复"],
    style: "奇崛生新",
    category: "江西诗派",
  },

  // 南宋诗人
  {
    name: "陆游",
    dynasty: "南宋",
    birth: 1125,
    death: 1210,
    peakPeriod: { start: 1150, end: 1200 },
    description: "爱国诗人，存诗最多的诗人",
    famousWorks: ["示儿", "游山西村", "钗头凤"],
    style: "雄浑豪放",
    category: "爱国诗派",
  },
  {
    name: "辛弃疾",
    dynasty: "南宋",
    birth: 1140,
    death: 1207,
    peakPeriod: { start: 1165, end: 1200 },
    description: "豪放派词人代表，与苏轼并称苏辛",
    famousWorks: ["青玉案·元夕", "破阵子", "永遇乐·京口北固亭怀古"],
    style: "豪放激昂",
    category: "豪放派",
  },
  {
    name: "李清照",
    dynasty: "南宋",
    birth: 1084,
    death: 1155,
    peakPeriod: { start: 1110, end: 1145 },
    description: "婉约派词人代表，千古第一才女",
    famousWorks: ["声声慢", "如梦令", "一剪梅"],
    style: "清新婉约",
    category: "婉约派",
  },
  {
    name: "杨万里",
    dynasty: "南宋",
    birth: 1127,
    death: 1206,
    peakPeriod: { start: 1155, end: 1195 },
    description: "中兴四大诗人之一，诚斋体创始人",
    famousWorks: ["小池", "晓出净慈寺送林子方"],
    style: "活泼自然",
    category: "诚斋体",
  },
  {
    name: "范成大",
    dynasty: "南宋",
    birth: 1126,
    death: 1193,
    peakPeriod: { start: 1155, end: 1185 },
    description: "中兴四大诗人之一，田园诗成就突出",
    famousWorks: ["四时田园杂兴", "州桥"],
    style: "清新自然",
    category: "田园诗派",
  },
];

export default poets;
