const timeline = [
  {
    title: "唐高祖",
    name: "李渊",
    from: 618,
    to: 626,
    description: "神尧大圣大光孝皇帝，唐朝开国皇帝，年号武德",
  },
  {
    title: "唐太宗",
    name: "李世民",
    from: 626,
    to: 649,
    description: "文武大圣大广孝皇帝，高祖次子，年号贞观，开创贞观之治",
  },
  {
    title: "唐高宗",
    name: "李治",
    from: 649,
    to: 683,
    description: "天皇大圣大弘孝皇帝，太宗第九子，长孙皇后所生",
  },
  {
    title: "唐中宗",
    name: "李显",
    from: 683,
    to: 684,
    description: "大和大圣大昭孝皇帝，高宗第七子，武曌所生，后复位705-710年",
  },
  {
    title: "唐睿宗",
    name: "李旦",
    from: 684,
    to: 690,
    description: "玄真大圣大兴孝皇帝，高宗第九子，武曌所生，后复位710-712年",
  },
  {
    title: "武周",
    name: "武曌",
    from: 690,
    to: 705,
    description: "则天顺圣皇后，中国历史上唯一的女皇帝，年号天授等",
  },
  {
    title: "唐少帝",
    name: "李重茂",
    from: 710,
    to: 710,
    description: "中宗子，在位仅十天",
  },
  {
    title: "唐玄宗",
    name: "李隆基",
    from: 712,
    to: 756,
    description: "至道大圣大明孝皇帝，睿宗第三子，开创开元盛世",
  },
  {
    title: "唐肃宗",
    name: "李亨",
    from: 756,
    to: 762,
    description: "文明武德大圣大宣孝皇帝，玄宗第三子，安史之乱期间即位",
  },
  {
    title: "唐代宗",
    name: "李豫",
    from: 762,
    to: 779,
    description: "睿文孝武皇帝，肃宗长子，平定安史之乱",
  },
  {
    title: "唐德宗",
    name: "李适",
    from: 779,
    to: 805,
    description: "神武圣文皇帝，代宗长子，年号建中、兴元、贞元",
  },
  {
    title: "唐顺宗",
    name: "李诵",
    from: 805,
    to: 805,
    description: "至德弘道大圣大安孝皇帝，德宗长子，在位仅1年",
  },
  {
    title: "唐宪宗",
    name: "李纯",
    from: 805,
    to: 820,
    description: "昭文章武大圣至神孝皇帝，顺宗长子，年号元和",
  },
  {
    title: "唐穆宗",
    name: "李恒",
    from: 820,
    to: 824,
    description: "睿圣文惠孝皇帝，宪宗第三子，年号长庆",
  },
  {
    title: "唐敬宗",
    name: "李湛",
    from: 824,
    to: 826,
    description: "睿武昭愍孝皇帝，穆宗长子，年号宝历",
  },
  {
    title: "唐文宗",
    name: "李昂",
    from: 826,
    to: 840,
    description: "元圣昭献孝皇帝，穆宗第二子，年号大和、开成",
  },
  {
    title: "唐武宗",
    name: "李炎",
    from: 840,
    to: 846,
    description: "至道昭肃孝皇帝，穆宗第五子，年号会昌",
  },
  {
    title: "唐宣宗",
    name: "李忱",
    from: 846,
    to: 859,
    description: "元圣至明成武献文睿智章仁神聪懿道大孝皇帝，宪宗第十三子",
  },
  {
    title: "唐懿宗",
    name: "李漼",
    from: 859,
    to: 873,
    description: "昭圣恭惠孝皇帝，宣宗长子，年号咸通",
  },
  {
    title: "唐僖宗",
    name: "李儇",
    from: 873,
    to: 888,
    description: "惠圣恭定孝皇帝，懿宗第五子，黄巢起义期间在位",
  },
  {
    title: "唐昭宗",
    name: "李晔",
    from: 888,
    to: 904,
    description: "圣穆景文孝皇帝，懿宗第七子，唐朝末期皇帝",
  },
  {
    title: "唐哀帝",
    name: "李柷",
    from: 904,
    to: 907,
    description: "昭宣光烈孝皇帝，昭宗第九子，唐朝最后一位皇帝",
  },
];

export default timeline;
