import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const POETS = [
  {"name":"白居易","url":"https://cnkgraph.com/Api/Biography/Export/18804"},
  {"name":"包拯","url":"https://cnkgraph.com/Api/Biography/Export/23145"},
  {"name":"蔡京","url":"https://cnkgraph.com/Api/Biography/Export/31303"},
  {"name":"蔡伸","url":"https://cnkgraph.com/Api/Biography/Export/31339"},
  {"name":"蔡襄","url":"https://cnkgraph.com/Api/Biography/Export/29849"},
  {"name":"蔡攸","url":"https://cnkgraph.com/Api/Biography/Export/31327"},
  {"name":"曹组","url":"https://cnkgraph.com/Api/Biography/Export/26688"},
  {"name":"岑参","url":"https://cnkgraph.com/Api/Biography/Export/14000"},
  {"name":"曾惇","url":"https://cnkgraph.com/Api/Biography/Export/26743"},
  {"name":"曾公亮","url":"https://cnkgraph.com/Api/Biography/Export/27293"},
  {"name":"曾巩","url":"https://cnkgraph.com/Api/Biography/Export/27305"},
  {"name":"曾几","url":"https://cnkgraph.com/Api/Biography/Export/27364"},
  {"name":"曾协","url":"https://cnkgraph.com/Api/Biography/Export/26720"},
  {"name":"曾慥","url":"https://cnkgraph.com/Api/Biography/Export/26744"},
  {"name":"曾肇","url":"https://cnkgraph.com/Api/Biography/Export/27329"},
  {"name":"晁补之","url":"https://cnkgraph.com/Api/Biography/Export/27339"},
  {"name":"晁冲之","url":"https://cnkgraph.com/Api/Biography/Export/26577"},
  {"name":"晁端礼","url":"https://cnkgraph.com/Api/Biography/Export/27327"},
  {"name":"晁端彦","url":"https://cnkgraph.com/Api/Biography/Export/27316"},
  {"name":"晁公武","url":"https://cnkgraph.com/Api/Biography/Export/26574"},
  {"name":"晁迥","url":"https://cnkgraph.com/Api/Biography/Export/26587"},
  {"name":"晁说之","url":"https://cnkgraph.com/Api/Biography/Export/27342"},
  {"name":"晁宗悫","url":"https://cnkgraph.com/Api/Biography/Export/26658"},
  {"name":"陈傅良","url":"https://cnkgraph.com/Api/Biography/Export/34539"},
  {"name":"陈瓘","url":"https://cnkgraph.com/Api/Biography/Export/34462"},
  {"name":"陈康伯","url":"https://cnkgraph.com/Api/Biography/Export/34494"},
  {"name":"陈亮","url":"https://cnkgraph.com/Api/Biography/Export/34547"},
  {"name":"陈人杰","url":"https://cnkgraph.com/Api/Biography/Export/34590"},
  {"name":"陈孺","url":"https://cnkgraph.com/Api/Biography/Export/26167"},
  {"name":"陈师道","url":"https://cnkgraph.com/Api/Biography/Export/34457"},
  {"name":"陈襄","url":"https://cnkgraph.com/Api/Biography/Export/34427"},
  {"name":"陈与义","url":"https://cnkgraph.com/Api/Biography/Export/34486"},
  {"name":"陈子昂","url":"https://cnkgraph.com/Api/Biography/Export/20887"},
  {"name":"程颢","url":"https://cnkgraph.com/Api/Biography/Export/29916"},
  {"name":"程俱","url":"https://cnkgraph.com/Api/Biography/Export/30728"},
  {"name":"程颐","url":"https://cnkgraph.com/Api/Biography/Export/29922"},
  {"name":"崔融","url":"https://cnkgraph.com/Api/Biography/Export/14914"},
  {"name":"崔涂","url":"https://cnkgraph.com/Api/Biography/Export/14668"},
  {"name":"崔与之","url":"https://cnkgraph.com/Api/Biography/Export/25201"},
  {"name":"戴复古","url":"https://cnkgraph.com/Api/Biography/Export/26391"},
  {"name":"邓肃","url":"https://cnkgraph.com/Api/Biography/Export/33058"},
  {"name":"丁谓","url":"https://cnkgraph.com/Api/Biography/Export/21993"},
  {"name":"独孤及","url":"https://cnkgraph.com/Api/Biography/Export/18488"},
  {"name":"杜范","url":"https://cnkgraph.com/Api/Biography/Export/28665"},
  {"name":"杜甫","url":"https://cnkgraph.com/Api/Biography/Export/17270"},
  {"name":"杜牧","url":"https://cnkgraph.com/Api/Biography/Export/17274"},
  {"name":"杜审言","url":"https://cnkgraph.com/Api/Biography/Export/17226"},
  {"name":"杜荀鹤","url":"https://cnkgraph.com/Api/Biography/Export/17287"},
  {"name":"度正","url":"https://cnkgraph.com/Api/Biography/Export/25224"},
  {"name":"段成式","url":"https://cnkgraph.com/Api/Biography/Export/17780"},
  {"name":"范成大","url":"https://cnkgraph.com/Api/Biography/Export/31372"},
  {"name":"范端臣","url":"https://cnkgraph.com/Api/Biography/Export/31562"},
  {"name":"范浚","url":"https://cnkgraph.com/Api/Biography/Export/31353"},
  {"name":"范寥","url":"https://cnkgraph.com/Api/Biography/Export/31522"},
  {"name":"范仲淹","url":"https://cnkgraph.com/Api/Biography/Export/29783"},
  {"name":"方干","url":"https://cnkgraph.com/Api/Biography/Export/16066"},
  {"name":"方岳","url":"https://cnkgraph.com/Api/Biography/Export/26438"},
  {"name":"冯京","url":"https://cnkgraph.com/Api/Biography/Export/22649"},
  {"name":"冯延巳","url":"https://cnkgraph.com/Api/Biography/Export/14737"},
  {"name":"富弼","url":"https://cnkgraph.com/Api/Biography/Export/24790"},
  {"name":"高适","url":"https://cnkgraph.com/Api/Biography/Export/21646"},
  {"name":"葛立方","url":"https://cnkgraph.com/Api/Biography/Export/31693"},
  {"name":"葛胜仲","url":"https://cnkgraph.com/Api/Biography/Export/31324"},
  {"name":"顾非熊","url":"https://cnkgraph.com/Api/Biography/Export/21686"},
  {"name":"管鉴","url":"https://cnkgraph.com/Api/Biography/Export/30927"},
  {"name":"贯休","url":"https://cnkgraph.com/Api/Biography/Export/20065"},
  {"name":"韩绛","url":"https://cnkgraph.com/Api/Biography/Export/34418"},
  {"name":"韩琦","url":"https://cnkgraph.com/Api/Biography/Export/34411"},
  {"name":"韩世忠","url":"https://cnkgraph.com/Api/Biography/Export/34485"},
  {"name":"韩维","url":"https://cnkgraph.com/Api/Biography/Export/34428"},
  {"name":"韩偓","url":"https://cnkgraph.com/Api/Biography/Export/21436"},
  {"name":"韩愈","url":"https://cnkgraph.com/Api/Biography/Export/21679"},
  {"name":"韩元吉","url":"https://cnkgraph.com/Api/Biography/Export/34515"},
  {"name":"何大圭","url":"https://cnkgraph.com/Api/Biography/Export/25056"},
  {"name":"贺铸","url":"https://cnkgraph.com/Api/Biography/Export/32277"},
  {"name":"洪皓","url":"https://cnkgraph.com/Api/Biography/Export/28560"},
  {"name":"洪迈","url":"https://cnkgraph.com/Api/Biography/Export/28601"},
  {"name":"洪适","url":"https://cnkgraph.com/Api/Biography/Export/28592"},
  {"name":"洪遵","url":"https://cnkgraph.com/Api/Biography/Export/28598"},
  {"name":"胡铨","url":"https://cnkgraph.com/Api/Biography/Export/31351"},
  {"name":"胡舜陟","url":"https://cnkgraph.com/Api/Biography/Export/31334"},
  {"name":"胡宪","url":"https://cnkgraph.com/Api/Biography/Export/31189"},
  {"name":"胡瑗","url":"https://cnkgraph.com/Api/Biography/Export/29794"},
  {"name":"胡则","url":"https://cnkgraph.com/Api/Biography/Export/29738"},
  {"name":"胡仔","url":"https://cnkgraph.com/Api/Biography/Export/31143"},
  {"name":"皇甫湜","url":"https://cnkgraph.com/Api/Biography/Export/18842"},
  {"name":"黄次山","url":"https://cnkgraph.com/Api/Biography/Export/35681"},
  {"name":"黄大临","url":"https://cnkgraph.com/Api/Biography/Export/35631"},
  {"name":"黄榦","url":"https://cnkgraph.com/Api/Biography/Export/35669"},
  {"name":"黄公度","url":"https://cnkgraph.com/Api/Biography/Export/34505"},
  {"name":"黄昇","url":"https://cnkgraph.com/Api/Biography/Export/35611"},
  {"name":"黄滔","url":"https://cnkgraph.com/Api/Biography/Export/21690"},
  {"name":"黄庭坚","url":"https://cnkgraph.com/Api/Biography/Export/34455"},
  {"name":"惠洪","url":"https://cnkgraph.com/Api/Biography/Export/33754"},
  {"name":"贾岛","url":"https://cnkgraph.com/Api/Biography/Export/20204"},
  {"name":"江端友","url":"https://cnkgraph.com/Api/Biography/Export/28941"},
  {"name":"江万里","url":"https://cnkgraph.com/Api/Biography/Export/28902"},
  {"name":"姜夔","url":"https://cnkgraph.com/Api/Biography/Export/25195"},
  {"name":"蒋捷","url":"https://cnkgraph.com/Api/Biography/Export/31786"},
  {"name":"孔平仲","url":"https://cnkgraph.com/Api/Biography/Export/24326"},
  {"name":"孔文仲","url":"https://cnkgraph.com/Api/Biography/Export/24353"},
  {"name":"孔武仲","url":"https://cnkgraph.com/Api/Biography/Export/24355"},
  {"name":"寇准","url":"https://cnkgraph.com/Api/Biography/Export/24783"},
  {"name":"李翱","url":"https://cnkgraph.com/Api/Biography/Export/17014"},
  {"name":"李白","url":"https://cnkgraph.com/Api/Biography/Export/15188"},
  {"name":"李壁","url":"https://cnkgraph.com/Api/Biography/Export/27421"},
  {"name":"李曾伯","url":"https://cnkgraph.com/Api/Biography/Export/27282"},
  {"name":"李处全","url":"https://cnkgraph.com/Api/Biography/Export/27407"},
  {"name":"李德裕","url":"https://cnkgraph.com/Api/Biography/Export/16661"},
  {"name":"李侗","url":"https://cnkgraph.com/Api/Biography/Export/27373"},
  {"name":"李昉","url":"https://cnkgraph.com/Api/Biography/Export/21921"},
  {"name":"李纲","url":"https://cnkgraph.com/Api/Biography/Export/27793"},
  {"name":"李觏","url":"https://cnkgraph.com/Api/Biography/Export/27777"},
  {"name":"李光","url":"https://cnkgraph.com/Api/Biography/Export/27356"},
  {"name":"李贺","url":"https://cnkgraph.com/Api/Biography/Export/17089"},
  {"name":"李峤","url":"https://cnkgraph.com/Api/Biography/Export/15132"},
  {"name":"李璟","url":"https://cnkgraph.com/Api/Biography/Export/16924"},
  {"name":"李昴英","url":"https://cnkgraph.com/Api/Biography/Export/27440"},
  {"name":"李弥逊","url":"https://cnkgraph.com/Api/Biography/Export/27370"},
  {"name":"李频","url":"https://cnkgraph.com/Api/Biography/Export/17168"},
  {"name":"李清照","url":"https://cnkgraph.com/Api/Biography/Export/27794"},
  {"name":"李如圭","url":"https://cnkgraph.com/Api/Biography/Export/27117"},
  {"name":"李商隐","url":"https://cnkgraph.com/Api/Biography/Export/16489"},
  {"name":"李绅","url":"https://cnkgraph.com/Api/Biography/Export/16981"},
  {"name":"李焘","url":"https://cnkgraph.com/Api/Biography/Export/27805"},
  {"name":"李煜","url":"https://cnkgraph.com/Api/Biography/Export/16875"},
  {"name":"李渊","url":"https://cnkgraph.com/Api/Biography/Export/13949"},
  {"name":"李正民","url":"https://cnkgraph.com/Api/Biography/Export/27471"},
  {"name":"李埴","url":"https://cnkgraph.com/Api/Biography/Export/27425"},
  {"name":"林逋","url":"https://cnkgraph.com/Api/Biography/Export/28438"},
  {"name":"林景熙","url":"https://cnkgraph.com/Api/Biography/Export/36815"},
  {"name":"令狐楚","url":"https://cnkgraph.com/Api/Biography/Export/14025"},
  {"name":"令狐绹","url":"https://cnkgraph.com/Api/Biography/Export/14630"},
  {"name":"刘昺","url":"https://cnkgraph.com/Api/Biography/Export/23000"},
  {"name":"刘才邵","url":"https://cnkgraph.com/Api/Biography/Export/25019"},
  {"name":"刘敞","url":"https://cnkgraph.com/Api/Biography/Export/22923"},
  {"name":"刘辰翁","url":"https://cnkgraph.com/Api/Biography/Export/36803"},
  {"name":"刘得仁","url":"https://cnkgraph.com/Api/Biography/Export/13178"},
  {"name":"刘过","url":"https://cnkgraph.com/Api/Biography/Export/25192"},
  {"name":"刘涣","url":"https://cnkgraph.com/Api/Biography/Export/22978"},
  {"name":"刘将孙","url":"https://cnkgraph.com/Api/Biography/Export/38035"},
  {"name":"刘克庄","url":"https://cnkgraph.com/Api/Biography/Export/25254"},
  {"name":"刘勉之","url":"https://cnkgraph.com/Api/Biography/Export/25032"},
  {"name":"刘恕","url":"https://cnkgraph.com/Api/Biography/Export/22892"},
  {"name":"刘焘","url":"https://cnkgraph.com/Api/Biography/Export/23002"},
  {"name":"刘一止","url":"https://cnkgraph.com/Api/Biography/Export/24997"},
  {"name":"刘禹锡","url":"https://cnkgraph.com/Api/Biography/Export/14603"},
  {"name":"刘爚","url":"https://cnkgraph.com/Api/Biography/Export/25174"},
  {"name":"刘长卿","url":"https://cnkgraph.com/Api/Biography/Export/13340"},
  {"name":"刘子翚","url":"https://cnkgraph.com/Api/Biography/Export/25057"},
  {"name":"柳开","url":"https://cnkgraph.com/Api/Biography/Export/28421"},
  {"name":"柳永","url":"https://cnkgraph.com/Api/Biography/Export/28448"},
  {"name":"柳宗元","url":"https://cnkgraph.com/Api/Biography/Export/17578"},
  {"name":"卢照邻","url":"https://cnkgraph.com/Api/Biography/Export/13478"},
  {"name":"卢祖皋","url":"https://cnkgraph.com/Api/Biography/Export/23213"},
  {"name":"陆龟蒙","url":"https://cnkgraph.com/Api/Biography/Export/21017"},
  {"name":"陆九渊","url":"https://cnkgraph.com/Api/Biography/Export/34542"},
  {"name":"陆秀夫","url":"https://cnkgraph.com/Api/Biography/Export/34600"},
  {"name":"陆游","url":"https://cnkgraph.com/Api/Biography/Export/34522"},
  {"name":"吕本中","url":"https://cnkgraph.com/Api/Biography/Export/25014"},
  {"name":"吕胜己","url":"https://cnkgraph.com/Api/Biography/Export/23595"},
  {"name":"吕陶","url":"https://cnkgraph.com/Api/Biography/Export/23614"},
  {"name":"吕温","url":"https://cnkgraph.com/Api/Biography/Export/14605"},
  {"name":"吕颐浩","url":"https://cnkgraph.com/Api/Biography/Export/24979"},
  {"name":"吕祖谦","url":"https://cnkgraph.com/Api/Biography/Export/25154"},
  {"name":"罗从彦","url":"https://cnkgraph.com/Api/Biography/Export/30981"},
  {"name":"罗隐","url":"https://cnkgraph.com/Api/Biography/Export/19207"},
  {"name":"骆宾王","url":"https://cnkgraph.com/Api/Biography/Export/21620"},
  {"name":"马端临","url":"https://cnkgraph.com/Api/Biography/Export/35533"},
  {"name":"马廷鸾","url":"https://cnkgraph.com/Api/Biography/Export/35528"},
  {"name":"梅尧臣","url":"https://cnkgraph.com/Api/Biography/Export/28460"},
  {"name":"孟浩然","url":"https://cnkgraph.com/Api/Biography/Export/13993"},
  {"name":"孟郊","url":"https://cnkgraph.com/Api/Biography/Export/14010"},
  {"name":"米芾","url":"https://cnkgraph.com/Api/Biography/Export/30934"},
  {"name":"倪称","url":"https://cnkgraph.com/Api/Biography/Export/25086"},
  {"name":"牛僧孺","url":"https://cnkgraph.com/Api/Biography/Export/18505"},
  {"name":"欧阳修","url":"https://cnkgraph.com/Api/Biography/Export/28466"},
  {"name":"潘阆","url":"https://cnkgraph.com/Api/Biography/Export/29311"},
  {"name":"潘良贵","url":"https://cnkgraph.com/Api/Biography/Export/28569"},
  {"name":"皮日休","url":"https://cnkgraph.com/Api/Biography/Export/18853"},
  {"name":"綦崇礼","url":"https://cnkgraph.com/Api/Biography/Export/30943"},
  {"name":"钱起","url":"https://cnkgraph.com/Api/Biography/Export/20818"},
  {"name":"秦观","url":"https://cnkgraph.com/Api/Biography/Export/30713"},
  {"name":"秦桧","url":"https://cnkgraph.com/Api/Biography/Export/30714"},
  {"name":"丘崇","url":"https://cnkgraph.com/Api/Biography/Export/25145"},
  {"name":"权德舆","url":"https://cnkgraph.com/Api/Biography/Export/15294"},
  {"name":"沈端节","url":"https://cnkgraph.com/Api/Biography/Export/29139"},
  {"name":"沈焕","url":"https://cnkgraph.com/Api/Biography/Export/28629"},
  {"name":"沈括","url":"https://cnkgraph.com/Api/Biography/Export/28492"},
  {"name":"沈佺期","url":"https://cnkgraph.com/Api/Biography/Export/17898"},
  {"name":"沈瀛","url":"https://cnkgraph.com/Api/Biography/Export/29132"},
  {"name":"沈与求","url":"https://cnkgraph.com/Api/Biography/Export/28554"},
  {"name":"施宿","url":"https://cnkgraph.com/Api/Biography/Export/26523"},
  {"name":"施元之","url":"https://cnkgraph.com/Api/Biography/Export/26514"},
  {"name":"石介","url":"https://cnkgraph.com/Api/Biography/Export/29818"},
  {"name":"释保暹","url":"https://cnkgraph.com/Api/Biography/Export/33552"},
  {"name":"释惠崇","url":"https://cnkgraph.com/Api/Biography/Export/33793"},
  {"name":"释简长","url":"https://cnkgraph.com/Api/Biography/Export/34011"},
  {"name":"释惟凤","url":"https://cnkgraph.com/Api/Biography/Export/33780"},
  {"name":"释文兆","url":"https://cnkgraph.com/Api/Biography/Export/33826"},
  {"name":"释希昼","url":"https://cnkgraph.com/Api/Biography/Export/33713"},
  {"name":"释行肇","url":"https://cnkgraph.com/Api/Biography/Export/34040"},
  {"name":"释宇昭","url":"https://cnkgraph.com/Api/Biography/Export/33656"},
  {"name":"释知礼","url":"https://cnkgraph.com/Api/Biography/Export/29726"},
  {"name":"释仲殊","url":"https://cnkgraph.com/Api/Biography/Export/22186"},
  {"name":"释宗杲","url":"https://cnkgraph.com/Api/Biography/Export/33683"},
  {"name":"舒岳祥","url":"https://cnkgraph.com/Api/Biography/Export/31402"},
  {"name":"司空图","url":"https://cnkgraph.com/Api/Biography/Export/14662"},
  {"name":"宋白","url":"https://cnkgraph.com/Api/Biography/Export/24776"},
  {"name":"宋敏求","url":"https://cnkgraph.com/Api/Biography/Export/24794"},
  {"name":"宋祁","url":"https://cnkgraph.com/Api/Biography/Export/24788"},
  {"name":"宋庠","url":"https://cnkgraph.com/Api/Biography/Export/24786"},
  {"name":"宋之问","url":"https://cnkgraph.com/Api/Biography/Export/13975"},
  {"name":"苏过","url":"https://cnkgraph.com/Api/Biography/Export/31323"},
  {"name":"苏轼","url":"https://cnkgraph.com/Api/Biography/Export/29937"},
  {"name":"苏舜钦","url":"https://cnkgraph.com/Api/Biography/Export/29828"},
  {"name":"苏颂","url":"https://cnkgraph.com/Api/Biography/Export/29870"},
  {"name":"苏颋","url":"https://cnkgraph.com/Api/Biography/Export/19372"},
  {"name":"苏味道","url":"https://cnkgraph.com/Api/Biography/Export/19357"},
  {"name":"苏庠","url":"https://cnkgraph.com/Api/Biography/Export/31316"},
  {"name":"苏洵","url":"https://cnkgraph.com/Api/Biography/Export/29837"},
  {"name":"苏辙","url":"https://cnkgraph.com/Api/Biography/Export/29941"},
  {"name":"苏籀","url":"https://cnkgraph.com/Api/Biography/Export/31344"},
  {"name":"孙觌","url":"https://cnkgraph.com/Api/Biography/Export/25005"},
  {"name":"孙觉","url":"https://cnkgraph.com/Api/Biography/Export/24451"},
  {"name":"唐庚","url":"https://cnkgraph.com/Api/Biography/Export/24980"},
  {"name":"唐彦谦","url":"https://cnkgraph.com/Api/Biography/Export/13917"},
  {"name":"唐仲友","url":"https://cnkgraph.com/Api/Biography/Export/25152"},
  {"name":"田锡","url":"https://cnkgraph.com/Api/Biography/Export/29680"},
  {"name":"汪元量","url":"https://cnkgraph.com/Api/Biography/Export/36812"},
  {"name":"汪藻","url":"https://cnkgraph.com/Api/Biography/Export/28543"},
  {"name":"王安石","url":"https://cnkgraph.com/Api/Biography/Export/29874"},
  {"name":"王勃","url":"https://cnkgraph.com/Api/Biography/Export/18262"},
  {"name":"王昌龄","url":"https://cnkgraph.com/Api/Biography/Export/18440"},
  {"name":"王观","url":"https://cnkgraph.com/Api/Biography/Export/30322"},
  {"name":"王绩","url":"https://cnkgraph.com/Api/Biography/Export/12422"},
  {"name":"王建","url":"https://cnkgraph.com/Api/Biography/Export/18501"},
  {"name":"王令","url":"https://cnkgraph.com/Api/Biography/Export/28494"},
  {"name":"王迈","url":"https://cnkgraph.com/Api/Biography/Export/30426"},
  {"name":"王明清","url":"https://cnkgraph.com/Api/Biography/Export/30074"},
  {"name":"王阮","url":"https://cnkgraph.com/Api/Biography/Export/30402"},
  {"name":"王韶","url":"https://cnkgraph.com/Api/Biography/Export/29907"},
  {"name":"王十朋","url":"https://cnkgraph.com/Api/Biography/Export/28586"},
  {"name":"王遂","url":"https://cnkgraph.com/Api/Biography/Export/30377"},
  {"name":"王庭珪","url":"https://cnkgraph.com/Api/Biography/Export/29988"},
  {"name":"王维","url":"https://cnkgraph.com/Api/Biography/Export/18616"},
  {"name":"王炎","url":"https://cnkgraph.com/Api/Biography/Export/30187"},
  {"name":"王沂孙","url":"https://cnkgraph.com/Api/Biography/Export/30150"},
  {"name":"王以宁","url":"https://cnkgraph.com/Api/Biography/Export/29441"},
  {"name":"王应麟","url":"https://cnkgraph.com/Api/Biography/Export/29985"},
  {"name":"王禹偁","url":"https://cnkgraph.com/Api/Biography/Export/29711"},
  {"name":"王之涣","url":"https://cnkgraph.com/Api/Biography/Export/18220"},
  {"name":"王之望","url":"https://cnkgraph.com/Api/Biography/Export/28578"},
  {"name":"王质","url":"https://cnkgraph.com/Api/Biography/Export/30344"},
  {"name":"王铚","url":"https://cnkgraph.com/Api/Biography/Export/30396"},
  {"name":"王仲甫","url":"https://cnkgraph.com/Api/Biography/Export/29448"},
  {"name":"王灼","url":"https://cnkgraph.com/Api/Biography/Export/30186"},
  {"name":"韦应物","url":"https://cnkgraph.com/Api/Biography/Export/21277"},
  {"name":"韦庄","url":"https://cnkgraph.com/Api/Biography/Export/21282"},
  {"name":"魏了翁","url":"https://cnkgraph.com/Api/Biography/Export/35522"},
  {"name":"魏野","url":"https://cnkgraph.com/Api/Biography/Export/34390"},
  {"name":"魏征","url":"https://cnkgraph.com/Api/Biography/Export/12415"},
  {"name":"温庭筠","url":"https://cnkgraph.com/Api/Biography/Export/18032"},
  {"name":"文天祥","url":"https://cnkgraph.com/Api/Biography/Export/26406"},
  {"name":"文彦博","url":"https://cnkgraph.com/Api/Biography/Export/26200"},
  {"name":"无可","url":"https://cnkgraph.com/Api/Biography/Export/16084"},
  {"name":"吴芾","url":"https://cnkgraph.com/Api/Biography/Export/25062"},
  {"name":"吴潜","url":"https://cnkgraph.com/Api/Biography/Export/25271"},
  {"name":"吴融","url":"https://cnkgraph.com/Api/Biography/Export/13770"},
  {"name":"吴文英","url":"https://cnkgraph.com/Api/Biography/Export/25279"},
  {"name":"吴中复","url":"https://cnkgraph.com/Api/Biography/Export/23621"},
  {"name":"武元衡","url":"https://cnkgraph.com/Api/Biography/Export/17734"},
  {"name":"夏竦","url":"https://cnkgraph.com/Api/Biography/Export/24192"},
  {"name":"向子諲","url":"https://cnkgraph.com/Api/Biography/Export/25017"},
  {"name":"项斯","url":"https://cnkgraph.com/Api/Biography/Export/21688"},
  {"name":"萧德藻","url":"https://cnkgraph.com/Api/Biography/Export/31647"},
  {"name":"萧颖士","url":"https://cnkgraph.com/Api/Biography/Export/19511"},
  {"name":"谢翱","url":"https://cnkgraph.com/Api/Biography/Export/32291"},
  {"name":"谢枋得","url":"https://cnkgraph.com/Api/Biography/Export/32247"},
  {"name":"谢薖","url":"https://cnkgraph.com/Api/Biography/Export/32282"},
  {"name":"谢逸","url":"https://cnkgraph.com/Api/Biography/Export/32281"},
  {"name":"辛弃疾","url":"https://cnkgraph.com/Api/Biography/Export/32928"},
  {"name":"徐俯","url":"https://cnkgraph.com/Api/Biography/Export/26215"},
  {"name":"徐积","url":"https://cnkgraph.com/Api/Biography/Export/26204"},
  {"name":"徐鹿卿","url":"https://cnkgraph.com/Api/Biography/Export/26396"},
  {"name":"徐梦莘","url":"https://cnkgraph.com/Api/Biography/Export/26375"},
  {"name":"徐铉","url":"https://cnkgraph.com/Api/Biography/Export/15869"},
  {"name":"许棐","url":"https://cnkgraph.com/Api/Biography/Export/32163"},
  {"name":"许浑","url":"https://cnkgraph.com/Api/Biography/Export/19980"},
  {"name":"薛季宣","url":"https://cnkgraph.com/Api/Biography/Export/31376"},
  {"name":"薛能","url":"https://cnkgraph.com/Api/Biography/Export/19677"},
  {"name":"严羽","url":"https://cnkgraph.com/Api/Biography/Export/25262"},
  {"name":"颜真卿","url":"https://cnkgraph.com/Api/Biography/Export/21650"},
  {"name":"晏几道","url":"https://cnkgraph.com/Api/Biography/Export/27313"},
  {"name":"晏殊","url":"https://cnkgraph.com/Api/Biography/Export/27290"},
  {"name":"扬无咎","url":"https://cnkgraph.com/Api/Biography/Export/27996"},
  {"name":"阳枋","url":"https://cnkgraph.com/Api/Biography/Export/34576"},
  {"name":"杨绘","url":"https://cnkgraph.com/Api/Biography/Export/28486"},
  {"name":"杨简","url":"https://cnkgraph.com/Api/Biography/Export/28632"},
  {"name":"杨炯","url":"https://cnkgraph.com/Api/Biography/Export/17397"},
  {"name":"杨凝式","url":"https://cnkgraph.com/Api/Biography/Export/17347"},
  {"name":"杨时","url":"https://cnkgraph.com/Api/Biography/Export/27995"},
  {"name":"杨万里","url":"https://cnkgraph.com/Api/Biography/Export/27865"},
  {"name":"杨亿","url":"https://cnkgraph.com/Api/Biography/Export/27871"},
  {"name":"杨缵","url":"https://cnkgraph.com/Api/Biography/Export/28059"},
  {"name":"姚合","url":"https://cnkgraph.com/Api/Biography/Export/14610"},
  {"name":"姚勉","url":"https://cnkgraph.com/Api/Biography/Export/25302"},
  {"name":"叶梦得","url":"https://cnkgraph.com/Api/Biography/Export/24994"},
  {"name":"叶适","url":"https://cnkgraph.com/Api/Biography/Export/25184"},
  {"name":"尹焞","url":"https://cnkgraph.com/Api/Biography/Export/24983"},
  {"name":"尹洙","url":"https://cnkgraph.com/Api/Biography/Export/24789"},
  {"name":"雍陶","url":"https://cnkgraph.com/Api/Biography/Export/21195"},
  {"name":"尤袤","url":"https://cnkgraph.com/Api/Biography/Export/25130"},
  {"name":"游酢","url":"https://cnkgraph.com/Api/Biography/Export/28519"},
  {"name":"余靖","url":"https://cnkgraph.com/Api/Biography/Export/22408"},
  {"name":"鱼玄机","url":"https://cnkgraph.com/Api/Biography/Export/21691"},
  {"name":"宇文虚中","url":"https://cnkgraph.com/Api/Biography/Export/36002"},
  {"name":"喻凫","url":"https://cnkgraph.com/Api/Biography/Export/14036"},
  {"name":"元结","url":"https://cnkgraph.com/Api/Biography/Export/12931"},
  {"name":"元稹","url":"https://cnkgraph.com/Api/Biography/Export/14615"},
  {"name":"袁枢","url":"https://cnkgraph.com/Api/Biography/Export/31375"},
  {"name":"袁说友","url":"https://cnkgraph.com/Api/Biography/Export/31386"},
  {"name":"岳飞","url":"https://cnkgraph.com/Api/Biography/Export/25061"},
  {"name":"岳珂","url":"https://cnkgraph.com/Api/Biography/Export/25249"},
  {"name":"张昪","url":"https://cnkgraph.com/Api/Biography/Export/25668"},
  {"name":"张彻","url":"https://cnkgraph.com/Api/Biography/Export/15470"},
  {"name":"张方平","url":"https://cnkgraph.com/Api/Biography/Export/25657"},
  {"name":"张籍","url":"https://cnkgraph.com/Api/Biography/Export/15628"},
  {"name":"张九成","url":"https://cnkgraph.com/Api/Biography/Export/25409"},
  {"name":"张九龄","url":"https://cnkgraph.com/Api/Biography/Export/15164"},
  {"name":"张耒","url":"https://cnkgraph.com/Api/Biography/Export/25820"},
  {"name":"张栻","url":"https://cnkgraph.com/Api/Biography/Export/25690"},
  {"name":"张守","url":"https://cnkgraph.com/Api/Biography/Export/25545"},
  {"name":"张说","url":"https://cnkgraph.com/Api/Biography/Export/15153"},
  {"name":"张先","url":"https://cnkgraph.com/Api/Biography/Export/25437"},
  {"name":"张孝祥","url":"https://cnkgraph.com/Api/Biography/Export/25540"},
  {"name":"张炎","url":"https://cnkgraph.com/Api/Biography/Export/25750"},
  {"name":"张元干","url":"https://cnkgraph.com/Api/Biography/Export/25448"},
  {"name":"张载","url":"https://cnkgraph.com/Api/Biography/Export/25872"},
  {"name":"章楶","url":"https://cnkgraph.com/Api/Biography/Export/29892"},
  {"name":"赵抃","url":"https://cnkgraph.com/Api/Biography/Export/29834"},
  {"name":"赵鼎","url":"https://cnkgraph.com/Api/Biography/Export/32920"},
  {"name":"赵以夫","url":"https://cnkgraph.com/Api/Biography/Export/32438"},
  {"name":"郑伯熊","url":"https://cnkgraph.com/Api/Biography/Export/33171"},
  {"name":"郑巢","url":"https://cnkgraph.com/Api/Biography/Export/20541"},
  {"name":"郑刚中","url":"https://cnkgraph.com/Api/Biography/Export/33190"},
  {"name":"郑谷","url":"https://cnkgraph.com/Api/Biography/Export/20907"},
  {"name":"郑獬","url":"https://cnkgraph.com/Api/Biography/Export/29879"},
  {"name":"郑兴裔","url":"https://cnkgraph.com/Api/Biography/Export/33191"},
  {"name":"周邦彦","url":"https://cnkgraph.com/Api/Biography/Export/24955"},
  {"name":"周必大","url":"https://cnkgraph.com/Api/Biography/Export/25121"},
  {"name":"周敦颐","url":"https://cnkgraph.com/Api/Biography/Export/23943"},
  {"name":"周贺","url":"https://cnkgraph.com/Api/Biography/Export/13876"},
  {"name":"周葵","url":"https://cnkgraph.com/Api/Biography/Export/25051"},
  {"name":"周密","url":"https://cnkgraph.com/Api/Biography/Export/25316"},
  {"name":"朱敦儒","url":"https://cnkgraph.com/Api/Biography/Export/27361"},
  {"name":"朱松","url":"https://cnkgraph.com/Api/Biography/Export/27377"},
  {"name":"朱熹","url":"https://cnkgraph.com/Api/Biography/Export/27404"},
  {"name":"宗泽","url":"https://cnkgraph.com/Api/Biography/Export/24962"},
  {"name":"邹浩","url":"https://cnkgraph.com/Api/Biography/Export/33143"}
];

const outDir = process.env.SXG_OUT || path.resolve(__dirname, "../src/datacsv");
const cookieFile = path.join(__dirname, ".cnkgraph.cookies");
const cookie = process.env.SXG_COOKIE || (fs.existsSync(cookieFile) ? fs.readFileSync(cookieFile, "utf-8").trim() : "");
const force = process.argv.includes("--force");

const HEADERS = ["朝代", "作家", "皇帝年号及干支", "年份", "录入者"];

const sanitize = (name) => name.replace(/[\\/:*?"<>|]/g, "").trim();
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function fetchCsv(url) {
  let wait = 3000;
  for (let a = 0; a < 8; a++) {
    const res = await fetch(url, {
      headers: {
        Cookie: cookie,
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36",
        Referer: "https://cnkgraph.com/Map/PoetLife#main",
        Accept: "text/csv, application/json;q=0.9, */*;q=0.8",
      },
    });
    if (res.status === 429) {
      console.log("  429, backoff", wait, "ms");
      await sleep(wait);
      wait *= 2;
      continue;
    }
    if (!res.ok) throw new Error("HTTP " + res.status);
    return Buffer.from(await res.arrayBuffer());
  }
  throw new Error("HTTP 429 after retries");
}

let ok = 0;
let skipped = 0;
const failed = [];
for (const p of POETS) {
  const fname = "行迹_" + sanitize(p.name) + ".csv";
  const fpath = path.join(outDir, fname);
  if (!force && fs.existsSync(fpath)) {
    skipped++;
    continue;
  }
  try {
    const buf = await fetchCsv(p.url);
    const text = buf.toString("utf-8");
    if (!HEADERS.every((h) => text.includes(h))) throw new Error("bad csv len=" + buf.length);
    fs.writeFileSync(fpath, text);
    ok++;
    console.log("OK", fname, buf.length);
  } catch (e) {
    failed.push(fname);
    console.error("FAIL", fname, String(e));
  }
  await sleep(400 + Math.random() * 300);
  if ((ok + skipped) % 50 === 0) console.log("progress ok=", ok, "skipped=", skipped, "failed=", failed.length);
}
console.log("DONE ok=", ok, "skipped=", skipped, "failed=", failed.length, JSON.stringify(failed));

